language: node_js
node_js:
- '8'
- 'node'
deploy:
  provider: npm
  email: carlos.buendia@helena.network
  api_key: $NPM_TOKEN
  on:
    all_branches: true
    tags: true
    node: '8'
    repo: frontier-token-research/pm-helena-contracts
